id: P005441
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W22001
  title: གླིང་གེ་སར་རྒྱལ་པོའི་སྒྲུང་གདུག་པ་སྤུན་བདུན
  author: ''
  volumes:
    da803d52ef8644a58550eae171e87443:
      image_group_id: I1PD28070
      title: ''
      volume_number: 1
      total_pages: 606
      base_file: v001.txt
