id: IA96E261B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T20:28:01+00:00'
last_modified: '2022-06-08T03:06:42.571209+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22001
  title: གླིང་གེ་སར་རྒྱལ་པོའི་སྒྲུང་གདུག་པ་སྤུན་བདུན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    8B2E:
      image_group_id: I1PD28070
      title: ''
      total_pages: 606
      order: 1
      base_file: 8B2E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
